name: installer
description: Aliucord Installer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_intent_plus: ^3.1.6
  collection: ^1.17.0
  dio: ^5.0.0
  filesystem_picker: ^3.1.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
